import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";

const fontSans = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Causes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                elements: {
                    formButtonPrimary: "bg-purple-600 hover:bg-purple-400",
                    card: "ring-2 hover:ring-purple-600 active:ring-purple-600 bg-purple-50",
                },
            }}
        >
            <html lang='en'>
                <body
                    className={cn(
                        "min-h-screen bg-background font-sans antialiased",
                        fontSans.className
                    )}
                >
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='dark'
                        disableTransitionOnChange={false}
                    >
                        {children}
                        <Toaster />
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
